import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'carmore-icon',
      collapsible: true,
      collapsed: false,
      items: [
        'carmore-icon/overview',
        'carmore-icon/installation',
        'carmore-icon/usage',
        {
          type: 'category',
          label: 'Icons',
          collapsible: true,
          collapsed: false,
          items: [
            'carmore-icon/icons/arrow-double-down',
            'carmore-icon/icons/arrow-double-up',
            'carmore-icon/icons/arrow-down',
            'carmore-icon/icons/arrow-up',
            'carmore-icon/icons/back-btn',
            'carmore-icon/icons/cancel',
            'carmore-icon/icons/chat',
            'carmore-icon/icons/check',
            'carmore-icon/icons/copy',
            'carmore-icon/icons/copy-link',
            // 'carmore-icon/icons/country-flag-ae',
            // 'carmore-icon/icons/country-flag-al',
            // 'carmore-icon/icons/country-flag-ar',
            // 'carmore-icon/icons/country-flag-at',
            // 'carmore-icon/icons/country-flag-au',
            // 'carmore-icon/icons/country-flag-be',
            // 'carmore-icon/icons/country-flag-bg',
            // 'carmore-icon/icons/country-flag-ca',
            // 'carmore-icon/icons/country-flag-ch',
            // 'carmore-icon/icons/country-flag-cl',
            // 'carmore-icon/icons/country-flag-cr',
            // 'carmore-icon/icons/country-flag-cy',
            // 'carmore-icon/icons/country-flag-cz',
            // 'carmore-icon/icons/country-flag-de',
            // 'carmore-icon/icons/country-flag-dk',
            // 'carmore-icon/icons/country-flag-do',
            // 'carmore-icon/icons/country-flag-ec',
            // 'carmore-icon/icons/country-flag-ee',
            // 'carmore-icon/icons/country-flag-eg',
            // 'carmore-icon/icons/country-flag-es',
            // 'carmore-icon/icons/country-flag-fi',
            // 'carmore-icon/icons/country-flag-fj',
            // 'carmore-icon/icons/country-flag-fr',
            // 'carmore-icon/icons/country-flag-gb',
            // 'carmore-icon/icons/country-flag-ge',
            // 'carmore-icon/icons/country-flag-gr',
            // 'carmore-icon/icons/country-flag-hr',
            // 'carmore-icon/icons/country-flag-hu',
            // 'carmore-icon/icons/country-flag-ie',
            // 'carmore-icon/icons/country-flag-il',
            // 'carmore-icon/icons/country-flag-in',
            // 'carmore-icon/icons/country-flag-is',
            // 'carmore-icon/icons/country-flag-it',
            // 'carmore-icon/icons/country-flag-jm',
            // 'carmore-icon/icons/country-flag-jo',
            // 'carmore-icon/icons/country-flag-jp',
            // 'carmore-icon/icons/country-flag-kw',
            // 'carmore-icon/icons/country-flag-la',
            // 'carmore-icon/icons/country-flag-lk',
            // 'carmore-icon/icons/country-flag-lt',
            // 'carmore-icon/icons/country-flag-lu',
            // 'carmore-icon/icons/country-flag-lv',
            // 'carmore-icon/icons/country-flag-ma',
            // 'carmore-icon/icons/country-flag-me',
            // 'carmore-icon/icons/country-flag-mt',
            // 'carmore-icon/icons/country-flag-mu',
            // 'carmore-icon/icons/country-flag-mx',
            // 'carmore-icon/icons/country-flag-my',
            // 'carmore-icon/icons/country-flag-nl',
            // 'carmore-icon/icons/country-flag-no',
            // 'carmore-icon/icons/country-flag-nz',
            // 'carmore-icon/icons/country-flag-pa',
            // 'carmore-icon/icons/country-flag-pe',
            // 'carmore-icon/icons/country-flag-ph',
            // 'carmore-icon/icons/country-flag-pl',
            // 'carmore-icon/icons/country-flag-pt',
            // 'carmore-icon/icons/country-flag-py',
            // 'carmore-icon/icons/country-flag-qa',
            // 'carmore-icon/icons/country-flag-ro',
            // 'carmore-icon/icons/country-flag-rs',
            // 'carmore-icon/icons/country-flag-sa',
            // 'carmore-icon/icons/country-flag-se',
            // 'carmore-icon/icons/country-flag-sg',
            // 'carmore-icon/icons/country-flag-si',
            // 'carmore-icon/icons/country-flag-sk',
            // 'carmore-icon/icons/country-flag-th',
            // 'carmore-icon/icons/country-flag-tr',
            // 'carmore-icon/icons/country-flag-tw',
            // 'carmore-icon/icons/country-flag-us',
            // 'carmore-icon/icons/country-flag-vn',
            // 'carmore-icon/icons/country-flag-za',
            'carmore-icon/icons/cs',
            'carmore-icon/icons/download',
            // 'carmore-icon/icons/like',
            // 'carmore-icon/icons/loading-spinner',
            'carmore-icon/icons/nowhere',
            'carmore-icon/icons/out-link',
            'carmore-icon/icons/pin-map',
            // 'carmore-icon/icons/refresh',
            // 'carmore-icon/icons/reply',
            // 'carmore-icon/icons/search',
            'carmore-icon/icons/setting',
            'carmore-icon/icons/share',
            'carmore-icon/icons/stepper-minus',
            'carmore-icon/icons/stepper-plus',
            'carmore-icon/icons/switch-arrow',
            'carmore-icon/icons/thumb-up',
            'carmore-icon/icons/user',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
