import type { IconType } from '@/types/carmore-icon';

import React from 'react';

import Flex from '@/atoms/Flex';
import IconItem from '@/molecules/carmore-icon/IconItem';

const ICON_LIST: IconType[] = [
  'arrow-double-down',
  'arrow-double-up',
  'arrow-down',
  'arrow-up',
  'back-btn',
  'cancel',
  'chat',
  'check',
  'copy',
  'copy-link',
  'country-flag-ae',
  'country-flag-al',
  'country-flag-ar',
  'country-flag-at',
  'country-flag-au',
  'country-flag-be',
  'country-flag-bg',
  'country-flag-ca',
  'country-flag-ch',
  'country-flag-cl',
  'country-flag-cr',
  'country-flag-cy',
  'country-flag-cz',
  'country-flag-de',
  'country-flag-dk',
  'country-flag-do',
  'country-flag-ec',
  'country-flag-ee',
  'country-flag-eg',
  'country-flag-es',
  'country-flag-fi',
  'country-flag-fj',
  'country-flag-fr',
  'country-flag-gb',
  'country-flag-ge',
  'country-flag-gr',
  'country-flag-hr',
  'country-flag-hu',
  'country-flag-ie',
  'country-flag-il',
  'country-flag-in',
  'country-flag-is',
  'country-flag-it',
  'country-flag-jm',
  'country-flag-jo',
  'country-flag-jp',
  'country-flag-kw',
  'country-flag-la',
  'country-flag-lk',
  'country-flag-lt',
  'country-flag-lu',
  'country-flag-lv',
  'country-flag-ma',
  'country-flag-me',
  'country-flag-mt',
  'country-flag-mu',
  'country-flag-mx',
  'country-flag-my',
  'country-flag-nl',
  'country-flag-no',
  'country-flag-nz',
  'country-flag-pa',
  'country-flag-pe',
  'country-flag-ph',
  'country-flag-pl',
  'country-flag-pt',
  'country-flag-py',
  'country-flag-qa',
  'country-flag-ro',
  'country-flag-rs',
  'country-flag-sa',
  'country-flag-se',
  'country-flag-sg',
  'country-flag-si',
  'country-flag-sk',
  'country-flag-th',
  'country-flag-tr',
  'country-flag-tw',
  'country-flag-us',
  'country-flag-vn',
  'country-flag-za',
  'cs',
  'download',
  'like',
  'loading-spinner',
  'nowhere',
  'out-link',
  'pin-map',
  'refresh',
  'reply',
  'search',
  'setting',
  'share',
  'stepper-minus',
  'stepper-plus',
  'switch-arrow',
  'thumb-up',
  'user',
];

const OverviewIconList = () => {
  return (
    <Flex fullWidth wrap={'wrap'} gap={'2rem'}>
      {ICON_LIST.map((icon) => {
        return <IconItem icon={icon} href={`/docs/carmore-icon/icons/${icon}`} />;
      })}
    </Flex>
  );
};

export default OverviewIconList;
