import type { IconType } from '@/types/carmore-icon';

type IIconItem = {
  [I in IconType]: {
    icon: IconType;
    detailPath: string;
    releasedVersion: string; // 최초 릴리즈 버전
    updatedVersion?: string; // 최근 업데이트(변경)된 버전
    deprecatedVersion?: string; // 사용 중단된 버전
  };
};

const ICON_ITEM_MAP: IIconItem = {
  // 1.3.0
  checklist: { icon: 'checklist', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/checklist' },
  'direction-up': { icon: 'direction-up', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/direction-up' },
  'error-info': { icon: 'error-info', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/error-info' },
  ev: { icon: 'ev', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/ev' },
  'fav-home': { icon: 'fav-home', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/fav-home' },
  'fav-office': { icon: 'fav-office', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/fav-office' },
  help: { icon: 'help', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/help' },
  'method-credit-card': { icon: 'method-credit-card', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/method-credit-card' },
  'more-info': { icon: 'more-info', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/more-info' },
  'new-car': { icon: 'new-car', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/new-car' },
  point: { icon: 'point', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/point' },
  status: { icon: 'status', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/status' },
  success: { icon: 'success', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/success' },
  'tab-alert': { icon: 'tab-alert', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/tab-alert' },
  'tab-day': { icon: 'tab-day', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/tab-day' },
  'tab-home': { icon: 'tab-home', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/tab-home' },
  'tab-hotel': { icon: 'tab-hotel', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/tab-hotel' },
  'tab-mypage': { icon: 'tab-mypage', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/tab-mypage' },
  time: { icon: 'time', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/time' },
  warning: { icon: 'warning', releasedVersion: '1.3.0', detailPath: 'carmore-icon/icons/warning' },

  // 1.2.1
  airport: { icon: 'airport', releasedVersion: '1.2.1', detailPath: 'carmore-icon/icons/airport' },
  anchor: { icon: 'anchor', releasedVersion: '1.2.1', detailPath: 'carmore-icon/icons/anchor' },
  bus: { icon: 'bus', releasedVersion: '1.2.1', detailPath: 'carmore-icon/icons/bus' },
  car: { icon: 'car', releasedVersion: '1.2.1', detailPath: 'carmore-icon/icons/car' },
  'rental-house': { icon: 'rental-house', releasedVersion: '1.2.1', detailPath: 'carmore-icon/icons/rental-house' },
  station: { icon: 'station', releasedVersion: '1.2.1', detailPath: 'carmore-icon/icons/station' },
  walk: { icon: 'walk', releasedVersion: '1.2.1', detailPath: 'carmore-icon/icons/walk' },
  'with-car': { icon: 'with-car', releasedVersion: '1.2.1', detailPath: 'carmore-icon/icons/with-car' },

  // 1.1.0
  'arrow-down-ktx': { icon: 'arrow-down-ktx', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/arrow-down-ktx' },
  'arrow-left': { icon: 'arrow-left', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/arrow-left' },
  'arrow-right': { icon: 'arrow-right', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/arrow-right' },
  'arrow-up-ktx': { icon: 'arrow-up-ktx', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/arrow-up-ktx' },
  call: { icon: 'call', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/call' },
  close: { icon: 'close', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/close' },
  edit: { icon: 'edit', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/edit' },
  filter: { icon: 'filter', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/filter' },
  global: { icon: 'global', releasedVersion: '1.1.0', updatedVersion: '1.3.0', detailPath: 'carmore-icon/icons/global' },
  'hotel-activity': { icon: 'hotel-activity', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-activity' },
  'hotel-business': { icon: 'hotel-business', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-business' },
  'hotel-credit-card': { icon: 'hotel-credit-card', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-credit-card' },
  'hotel-dining': { icon: 'hotel-dining', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-dining' },
  'hotel-etc': { icon: 'hotel-etc', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-etc' },
  'hotel-facilities': { icon: 'hotel-facilities', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-facilities' },
  'hotel-fitness': { icon: 'hotel-fitness', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-fitness' },
  'hotel-kids': { icon: 'hotel-kids', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-kids' },
  'hotel-parking': { icon: 'hotel-parking', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-parking' },
  'hotel-room': { icon: 'hotel-room', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-room' },
  'hotel-service': { icon: 'hotel-service', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-service' },
  'hotel-valet': { icon: 'hotel-valet', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-valet' },
  'hotel-wifi': { icon: 'hotel-wifi', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/hotel-wifi' },
  'input-delete': { icon: 'input-delete', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/input-delete' },
  jeju: { icon: 'jeju', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/jeju' },
  list: { icon: 'list', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/list' },
  'list-dot': { icon: 'list-dot', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/list-dot' },
  'list-inactive': { icon: 'list-inactive', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/list-inactive' },
  month: { icon: 'month', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/month' },
  'one-way': { icon: 'one-way', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/one-way' },
  'round-trip': { icon: 'round-trip', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/round-trip' },
  'star-single': { icon: 'star-single', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/star-single' },
  ulleongdo: { icon: 'ulleongdo', releasedVersion: '1.1.0', detailPath: 'carmore-icon/icons/ulleongdo' },

  // 1.0.0
  'arrow-double-down': { icon: 'arrow-double-down', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/arrow-double-down' },
  'arrow-double-up': { icon: 'arrow-double-up', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/arrow-double-up' },
  'arrow-down': { icon: 'arrow-down', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/arrow-down' },
  'arrow-up': { icon: 'arrow-up', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/arrow-up' },
  'back-btn': { icon: 'back-btn', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/back-btn' },
  cancel: { icon: 'cancel', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/cancel' },
  chat: { icon: 'chat', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/chat' },
  check: { icon: 'check', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/check' },
  copy: { icon: 'copy', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/copy' },
  'copy-link': { icon: 'copy-link', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/copy-link' },
  'country-flag-ae': { icon: 'country-flag-ae', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ae' },
  'country-flag-al': { icon: 'country-flag-al', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-al' },
  'country-flag-ar': { icon: 'country-flag-ar', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ar' },
  'country-flag-at': { icon: 'country-flag-at', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-at' },
  'country-flag-au': { icon: 'country-flag-au', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-au' },
  'country-flag-be': { icon: 'country-flag-be', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-be' },
  'country-flag-bg': { icon: 'country-flag-bg', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-bg' },
  'country-flag-ca': { icon: 'country-flag-ca', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ca' },
  'country-flag-ch': { icon: 'country-flag-ch', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ch' },
  'country-flag-cl': { icon: 'country-flag-cl', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-cl' },
  'country-flag-cr': { icon: 'country-flag-cr', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-cr' },
  'country-flag-cy': { icon: 'country-flag-cy', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-cy' },
  'country-flag-cz': { icon: 'country-flag-cz', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-cz' },
  'country-flag-de': { icon: 'country-flag-de', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-de' },
  'country-flag-dk': { icon: 'country-flag-dk', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-dk' },
  'country-flag-do': { icon: 'country-flag-do', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-do' },
  'country-flag-ec': { icon: 'country-flag-ec', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ec' },
  'country-flag-ee': { icon: 'country-flag-ee', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ee' },
  'country-flag-eg': { icon: 'country-flag-eg', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-eg' },
  'country-flag-es': { icon: 'country-flag-es', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-es' },
  'country-flag-fi': { icon: 'country-flag-fi', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-fi' },
  'country-flag-fj': { icon: 'country-flag-fj', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-fj' },
  'country-flag-fr': { icon: 'country-flag-fr', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-fr' },
  'country-flag-gb': { icon: 'country-flag-gb', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-gb' },
  'country-flag-ge': { icon: 'country-flag-ge', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ge' },
  'country-flag-gr': { icon: 'country-flag-gr', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-gr' },
  'country-flag-hr': { icon: 'country-flag-hr', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-hr' },
  'country-flag-hu': { icon: 'country-flag-hu', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-hu' },
  'country-flag-ie': { icon: 'country-flag-ie', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ie' },
  'country-flag-il': { icon: 'country-flag-il', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-il' },
  'country-flag-in': { icon: 'country-flag-in', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-in' },
  'country-flag-is': { icon: 'country-flag-is', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-is' },
  'country-flag-it': { icon: 'country-flag-it', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-it' },
  'country-flag-jm': { icon: 'country-flag-jm', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-jm' },
  'country-flag-jo': { icon: 'country-flag-jo', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-jo' },
  'country-flag-jp': { icon: 'country-flag-jp', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-jp' },
  'country-flag-kw': { icon: 'country-flag-kw', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-kw' },
  'country-flag-la': { icon: 'country-flag-la', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-la' },
  'country-flag-lk': { icon: 'country-flag-lk', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-lk' },
  'country-flag-lt': { icon: 'country-flag-lt', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-lt' },
  'country-flag-lu': { icon: 'country-flag-lu', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-lu' },
  'country-flag-lv': { icon: 'country-flag-lv', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-lv' },
  'country-flag-ma': { icon: 'country-flag-ma', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ma' },
  'country-flag-me': { icon: 'country-flag-me', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-me' },
  'country-flag-mt': { icon: 'country-flag-mt', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-mt' },
  'country-flag-mu': { icon: 'country-flag-mu', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-mu' },
  'country-flag-mx': { icon: 'country-flag-mx', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-mx' },
  'country-flag-my': { icon: 'country-flag-my', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-my' },
  'country-flag-nl': { icon: 'country-flag-nl', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-nl' },
  'country-flag-no': { icon: 'country-flag-no', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-no' },
  'country-flag-nz': { icon: 'country-flag-nz', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-nz' },
  'country-flag-pa': { icon: 'country-flag-pa', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-pa' },
  'country-flag-pe': { icon: 'country-flag-pe', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-pe' },
  'country-flag-ph': { icon: 'country-flag-ph', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ph' },
  'country-flag-pl': { icon: 'country-flag-pl', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-pl' },
  'country-flag-pt': { icon: 'country-flag-pt', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-pt' },
  'country-flag-py': { icon: 'country-flag-py', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-py' },
  'country-flag-qa': { icon: 'country-flag-qa', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-qa' },
  'country-flag-ro': { icon: 'country-flag-ro', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-ro' },
  'country-flag-rs': { icon: 'country-flag-rs', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-rs' },
  'country-flag-sa': { icon: 'country-flag-sa', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-sa' },
  'country-flag-se': { icon: 'country-flag-se', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-se' },
  'country-flag-sg': { icon: 'country-flag-sg', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-sg' },
  'country-flag-si': { icon: 'country-flag-si', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-si' },
  'country-flag-sk': { icon: 'country-flag-sk', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-sk' },
  'country-flag-th': { icon: 'country-flag-th', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-th' },
  'country-flag-tr': { icon: 'country-flag-tr', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-tr' },
  'country-flag-tw': { icon: 'country-flag-tw', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-tw' },
  'country-flag-us': { icon: 'country-flag-us', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-us' },
  'country-flag-vn': { icon: 'country-flag-vn', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-vn' },
  'country-flag-za': { icon: 'country-flag-za', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/country-flag-za' },
  cs: { icon: 'cs', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/cs' },
  download: { icon: 'download', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/download' },
  like: { icon: 'like', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/like' },
  'loading-spinner': { icon: 'loading-spinner', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/loading-spinner' },
  nowhere: { icon: 'nowhere', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/nowhere' },
  'out-link': { icon: 'out-link', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/out-link' },
  'pin-map': { icon: 'pin-map', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/pin-map' },
  refresh: { icon: 'refresh', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/refresh' },
  reply: { icon: 'reply', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/reply' },
  search: { icon: 'search', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/search' },
  setting: { icon: 'setting', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/setting' },
  share: { icon: 'share', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/share' },
  'stepper-minus': { icon: 'stepper-minus', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/stepper-minus' },
  'stepper-plus': { icon: 'stepper-plus', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/stepper-plus' },
  'switch-arrow': { icon: 'switch-arrow', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/switch-arrow' },
  'thumb-up': { icon: 'thumb-up', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/thumb-up' },
  user: { icon: 'user', releasedVersion: '1.0.0', detailPath: 'carmore-icon/icons/user' },
} as const;

const ICON_ITEM_LIST = Object.values(ICON_ITEM_MAP).sort((item1, item2) => {
  const icon1 = item1.icon.toString();
  const icon2 = item2.icon.toString();
  return icon1.localeCompare(icon2);
});

export { ICON_ITEM_LIST, ICON_ITEM_MAP };
